services:
  - type: web
    name: nohitatu-website-admin
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5173
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        value: Admin@123
      - key: SESSION_SECRET
        value: nohitatu-secret-key-production-change-me-2026
